language: python
python:
- '3.6'
script:
- pytest

deploy:
  provider: pypi
  user: ernestum
  password:
    secure: PzJ6x3Ff+w1QkdDlzdveSSxg4HNltuSNrErx5er9RHql5X0101bL7ogSFeTgvGs4zK2YCegnOgM3AUupG4+AImwgD8Byv5f3lTFYqUHJ+9hTJ4y7R91K/iGVBxGMW84AN/j4BGX/pYkXGcWhkIq7Odne0ZUduQySSJOUNem2570C4c93+ZBhM2w89UX9ryyAN+42IEp52/OtDRwBBPusU3Vr3VbfccvCKBJlQXdJPoPNvpBhvenoEqV4gKOkWHHjStWJb/BJJNBxeGF7m0EzaLMoZDl7AFjcWHD7pl9Ymr6LA/efsxa+qP3ulzOcssh+UyIKuVznyJiyYIdesQvwzDiCHmb7JO9dNYOGoA40HL517iUiGctIe+Tf0oXEmngiebvxHp1i84IlHF0KtlhrEmnu+fyu3+QIjWu3MOUMv50WHI1hNsS7DXELdroJM2JaFLim3hKISzgBYFu9PxGdqTW4SxSNUnKyNeSOxE6ovfSNphfZTk3UetaEreyG3SEOWtCJm+dPCIKLyYpuI2A3mI5r9gjKgupi2H+9yY+iMndrYFeffGoE+PESoDIcxDW+Igms1pp352KZSGoM2VySWGw88qnn98aF5G9WJTs/UFgDuM0t+K6KxDONVMbTDfiC81OSOKpGJi1iQ5pkvBLx8Yx/xHsWQJ5DtiDu3z2Xqqw=
  on:
    tags: true